modbus_address = "192.168.8.165:502"
poll_interval = 300

[mqtt]
broker = "tcp://mqtt.makerspace.dan-nixon.com:1883"
client_id = "makerspace-sensors-bridge-1"
username = "makerspace_sensors_bridge"
password = ""

[[sensors]]
topic = "makerspace/sensors/10/temperature"
source = { type = "Float32", register = 2068 }

[[sensors]]
topic = "makerspace/sensors/10/humidity"
source = { type = "Float32", register = 2080 }

[[sensors]]
topic = "makerspace/sensors/11/temperature"
source = { type = "Float32", register = 2070 }

[[sensors]]
topic = "makerspace/sensors/11/humidity"
source = { type = "Float32", register = 2082 }

[[sensors]]
topic = "makerspace/sensors/12/temperature"
source = { type = "Float32", register = 2072 }

[[sensors]]
topic = "makerspace/sensors/12/humidity"
source = { type = "Float32", register = 2084 }

[[sensors]]
topic = "makerspace/sensors/13/temperature"
source = { type = "Float32", register = 2074 }

[[sensors]]
topic = "makerspace/sensors/13/humidity"
source = { type = "Float32", register = 2086 }

[[sensors]]
topic = "makerspace/sensors/14/temperature"
source = { type = "Float32", register = 2076 }

[[sensors]]
topic = "makerspace/sensors/14/humidity"
source = { type = "Float32", register = 2088 }

[[sensors]]
topic = "makerspace/sensors/15/temperature"
source = { type = "Float32", register = 2078 }

[[sensors]]
topic = "makerspace/sensors/15/humidity"
source = { type = "Float32", register = 2090 }
